# docker-compose.yml - VOLLSTÄNDIG mit allen deinen Features
services:
  # OLLAMA SERVICE HINZUFÜGEN
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Flask App
      - "8000:8000" # ChromaDB
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=ollama:11434 # ← NUR DIESE ZEILE GEÄNDERT
      # Optional: Falls Sie Together.ai oder OpenAI verwenden
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    depends_on:
      - ollama # ← HINZUGEFÜGT
    volumes:
      # Daten persistent machen
      - ./data:/app/data
      - ./frontend:/app/frontend
      - ./chroma_data:/app/chroma_data
      # Logs persistent machen (optional)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck: # ← DEIN HEALTHCHECK BLEIBT
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Mehr Ressourcen für HuggingFace Model
    deploy: # ← DEINE MEMORY LIMITS BLEIBEN
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  ollama_data: # ← HINZUGEFÜGT
