# docker-compose.yml - Für Ihr System optimiert
services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Flask App
      - "8000:8000" # ChromaDB
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      # Optional: Falls Sie Together.ai oder OpenAI verwenden
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      # Daten persistent machen
      - ./data:/app/data
      - ./frontend:/app/frontend
      - ./chroma_data:/app/chroma_data
      # Logs persistent machen (optional)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Mehr Ressourcen für HuggingFace Model
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
